title: An Interesting Title
author: Yo soy Dan
email: nah@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I am building a website, apparently.  Look at me go!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  dkiltman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
